// Loads the sol trace corpus that supplies a replay session's token mass.
//
// WHY REPLAY AT ALL. A session only sheds when it outgrows its window, and at a realistic
// 251,520-token budget that costs several hundred thousand tokens of real work per
// boundary. Paying a model to generate that is what made the steer campaigns expensive and
// still bought one boundary. Replayed content is already written: it costs one request per
// boundary instead of hundreds, and it is IDENTICAL ACROSS ARMS, which removes the
// confound every live run carries, where each arm's agent takes its own path and every
// difference downstream is partly that.
//
// The corpus is greghavens/gpt-5.6-sol-coding-and-debugging-traces (CC BY 4.0), chosen
// because its teacher model IS the model the arms run, so replayed assistant turns are in
// the voice the model would have used. A corpus generated by another model would put the
// agent in someone else's transcript.
//
// Rows are CUMULATIVE PREFIXES, roughly twelve per trajectory: row k holds the first k
// assistant steps. Reconstruction keeps the longest prefix per (trajectory, part) and
// concatenates parts in order. Taking rows at face value would replay the same opening
// twelve times over.
import { createReadStream } from "node:fs";
import { createInterface } from "node:readline";

/** Pi counts context in characters and divides; the corpus is measured the same way. */
export const REPLAY_CHARS_PER_TOKEN = 4;

export const replayTokens = (chars) => Math.ceil(chars / REPLAY_CHARS_PER_TOKEN);

/** The roles a replayed message may carry. Anything else is a corpus we do not understand. */
export const REPLAY_ROLES = Object.freeze(["system", "user", "assistant", "tool"]);

export function messageChars(message) {
  const content = message?.content;
  if (typeof content === "string") return content.length;
  if (Array.isArray(content)) {
    return content.reduce((total, part) => total +
      (typeof part?.text === "string" ? part.text.length : JSON.stringify(part ?? "").length), 0);
  }
  return JSON.stringify(content ?? "").length;
}

export function trajectoryChars(messages) {
  return messages.reduce((total, message) => total + messageChars(message), 0);
}

/**
 * Streams the corpus and returns one entry per (trajectory, part), each carrying the
 * LONGEST prefix seen for it. Streaming rather than reading whole: the file is a gigabyte
 * and only the surviving prefixes are held.
 */
export async function loadTrajectories(path, { limit = Infinity, minMessages = 2 } = {}) {
  const best = new Map();
  const stream = createInterface({
    input: createReadStream(path, { encoding: "utf8" }),
    crlfDelay: Infinity,
  });
  let rows = 0;
  let skipped = 0;
  for await (const line of stream) {
    if (!line.trim()) continue;
    let row;
    try { row = JSON.parse(line); } catch { skipped += 1; continue; }
    rows += 1;
    const id = row.source_trajectory_id;
    const part = Number(row.trace_part ?? 1);
    if (typeof id !== "string" || !Array.isArray(row.messages)) { skipped += 1; continue; }
    const key = `${id}#${part}`;
    const previous = best.get(key);
    if (previous && previous.messages.length >= row.messages.length) continue;
    best.set(key, {
      id, part,
      parts: Number(row.trace_parts ?? 1),
      model: row.teacher_model,
      lang: row.lang,
      category: row.category,
      messages: row.messages,
    });
    if (best.size > limit * 4) break;
  }

  // Parts belong to one session and only mean anything in order.
  const byTrajectory = new Map();
  for (const entry of best.values()) {
    if (!byTrajectory.has(entry.id)) byTrajectory.set(entry.id, []);
    byTrajectory.get(entry.id).push(entry);
  }
  const out = [];
  for (const [id, entries] of byTrajectory) {
    entries.sort((left, right) => left.part - right.part);
    const messages = entries.flatMap((entry) => entry.messages);
    if (messages.length < minMessages) continue;
    out.push({
      id,
      model: entries[0].model,
      lang: entries[0].lang,
      category: entries[0].category,
      parts: entries.length,
      messages,
      chars: trajectoryChars(messages),
    });
  }
  out.sort((left, right) => right.chars - left.chars);
  return { trajectories: out.slice(0, limit === Infinity ? out.length : limit), rows, skipped };
}

/**
 * Normalises a corpus message into the shape Pi's session manager appends. Content is a
 * string in this corpus; a system message is demoted to user because a replayed session
 * has exactly one system prompt and it is not this one.
 */
export function toPiMessage(message) {
  const role = message.role === "system" ? "user" : message.role;
  const text = typeof message.content === "string"
    ? message.content
    : JSON.stringify(message.content ?? "");
  return { role, content: [{ type: "text", text }] };
}
