#!/bin/bash -p
set -eu

ROOT=$(CDPATH= cd -- "$(/usr/bin/dirname -- "$0")/.." && /bin/pwd)
unset QUORUM_PI_ROOT NODE_OPTIONS NODE_PATH NODE_EXTRA_CA_CERTS LD_PRELOAD LD_LIBRARY_PATH \
  BASH_ENV ENV NODE_TLS_REJECT_UNAUTHORIZED PI_CODING_AGENT_DIR OPENAI_BASE_URL OPENAI_API_BASE \
  HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY http_proxy https_proxy all_proxy no_proxy \
  SSL_CERT_FILE SSL_CERT_DIR DBUS_SESSION_BUS_ADDRESS \
  GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_COMMON_DIR GIT_OBJECT_DIRECTORY \
  GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_CONFIG GIT_CONFIG_GLOBAL GIT_CONFIG_SYSTEM \
  GIT_CONFIG_COUNT GIT_CONFIG_PARAMETERS GIT_CEILING_DIRECTORIES GIT_NAMESPACE
PATH=/usr/local/bin:/usr/bin:/bin
HOME=/home/shane
USER=shane
LOGNAME=shane
XDG_RUNTIME_DIR=/run/user/$(/usr/bin/id -u)
export PATH HOME USER LOGNAME XDG_RUNTIME_DIR
export QUORUM_CONTEXT_SOAK_SANITIZED=1
exec /usr/bin/node "$ROOT/scripts/adjudicate_pi_context_soak.mjs" "$@"
